version: '3'

services:
  sandbox_vite:
    image: 'alpine'
    command: ['sleep', 'infinity']

  admin_server:
    image: 'alpine'
    command: ['sleep', 'infinity']

  admin_server_esbuild:
    image: 'alpine'
    command: ['sleep', 'infinity']

  admin_server_vite:
    image: 'alpine'
    command: ['sleep', 'infinity']

  api:
    ports: ['3001:4000']

  adminer:
    ports: ['3002:8080']

  s3:
    command: 'server --address :3003 /data'
    ports: ['3003:3003']

  postgres:
    ports: ['3005:5432']
